import type { Metadata } from "next";

import "./globals.css";

import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { Toaster } from "react-hot-toast";
import { NextAuthProvider } from "@/lib/providers";
import Providers from "@/lib/tanstack";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ja">
      <NextAuthProvider>
        <body className="bg-layoutColor">
          <>
            <Toaster />
            <Providers>
              <Header />
              {children}
            </Providers>
            <Footer />
          </>
        </body>
      </NextAuthProvider>
    </html>
  );
}
